server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d301g98dl3ps739mlh4g-a:5432/sgdej_database_we14
    username: mudahama
    password: rnfufFhV2qIIskbqchNuA11vn9Vm33BA
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource.hikari:
    data-source-properties:
      sslmode: require

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: unibank.app.informations@gmail.com
    password: vmnh nxbj zqsv komd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true