spring:
  datasource:
    url: jdbc:postgresql://dpg-d2rbsdidbo4c73d48hi0-a:5432/sgedj
    username: mudahama
    password: QT5sn6vDmgHuM4naM8HJIpaEYsiHXOqM
    driver-class-name: org.postgresql.Driver
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource.hikari:
    data-source-properties:
      sslmode: require

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: unibank.app.informations@gmail.com
    password: vmnh nxbj zqsv komd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true