spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SGEDJ
    username: mudahama
    password: 7_mdh_79
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never